@startuml
!include <C4/C4_Context>

Person(marketolog, "Маркетолог", "Инициирует запуск на основе ожиданий клиентов")
Person(chef, "Шеф-повар", "Создаёт рецептуру, техкарты, состав блюда")
Person(technolog, "Технолог", "Координирует процесс внедрения, управляет workflow")
Person(dept_staff, "Сотрудник отдела", "Представитель закупок, логистики, HR,\nценообразования, производства, склада,\nклиентского опыта, маркетинга, аналитики")
Person(ba, "Бизнес-аналитик", "Формирует бизнес требования")
Person(sa, "Системный аналитик", "Ставит технические задачи на разработку и интеграцию")
Person(admin, "Администратор", "Управление СУДП")

System(plh, "СУДП", "Система управления добавления продуктов")

' Граница предприятия через обычный прямоугольник с группировкой
rectangle "Сеть «Замысловатость»" {
    System(erp, "Внутренние системы", "Управление складом, закупками,\nпроизводством, персоналом, заказами, логистикой, клиентским опытом, безопасностью, платежами, аналитика данных")
    System(apps, "Клиентские приложения", "Сайты, мобильные приложения,\nтерминалы самообслуживания")
    System(robots, "Конвейеры и роботы", "Оборудование кухни")
}


System_Ext(delivery, "Службы доставки", "UberUniverse Eats\nDeliverWorld")

' Взаимодействия пользователей
Rel(marketolog, plh, "использует")
Rel(chef, plh, "использует")
Rel(technolog, plh, "использует")
Rel(dept_staff, plh, "использует")
Rel(ba, plh, "использует")
Rel(sa, plh, "использует")
Rel(admin, plh, "использует")

' Публикация во внутренние системы
Rel(plh, erp, "интеграция")
Rel(plh, apps, "интеграция")
Rel(plh, robots, "интеграция")

' Публикация во внешние системы
Rel(plh, delivery, "интеграция")
@enduml